### PR TITLE
port to ts

### LINKED ISSUE #656: IDE (VSCode) confused?
### Steps to reproduce
1. Ensure that the `feathers-hooks-common` is installed.
2. Auto-import `alterItems` (VSCode IDE Quick fix ("blue lightbulb"))
3. Note that the FeathersJS app doesn't start: 
`Cannot find module 'feathers-hooks-common/types'`

### Expected behavior
The IDE shouldn't import from `feathers-hooks-common/types` but rather from `feathers-hooks-common`.

### Actual behavior
The IDE imports from `feathers-hooks-common/types`.

### System configuration

**Module versions** Probably this package / metadata.

**NodeJS version**: `v16.14.0`

**Operating System**: `Ubuntu 20.04.4 LTS` on `WSL 2` on Windows 10 `x64`

**Browser Version**: Chrome `98.0.4758.102`

**React Native Version**: (Not used)

**Module Loader**: `vite` (from example FeathersJS project)

### PR DESCRIPTION
**Pull request by fratzinger**
Move the code base to typescript. Just a refactor, nothing should break but imports from `require(feathers-hooks-common/lib/...)` or `require(feathers-hooks-common/types)`

We should make it a major version, just to be sure.

What do you think @daffl ?

Issues: closes #656
PRs: closes #662, #646, #634

### CODE REVIEW

**Comment by daffl** [comment]
Amazing! I wonder how many things for this would break/change with the latest v5. It does have a good chunk of TypeScript related changes - especially around the hook context.

**Comment by daffl** [comment]
We can totally merge this one first once you put it into the ready for review state.

**Comment by fratzinger** [comment]
It's ready 😊

**Review by indatawetrust — APPROVED** [review]

**Comment by fratzinger** [comment]
continuing on #663

**Pull request closed without merging**
