### PR TITLE
New softDelete for Feathers 4

### PR DESCRIPTION
**Pull request by daffl**
This pull request adds a new `softDelete` hook that works with the adapter changes in Feathers 4. It is more performant because it no longer needs to make additional calls can can be fully customized by dynamically creating the query for removed items and the data when it gets deleted.

`softDelete2` is now deprecated so related issues will be closed:

- Closes https://github.com/feathersjs-ecosystem/feathers-hooks-common/issues/532
- Closes https://github.com/feathersjs-ecosystem/feathers-hooks-common/issues/528
- Closes https://github.com/feathersjs-ecosystem/feathers-hooks-common/issues/524
- Closes https://github.com/feathersjs-ecosystem/feathers-hooks-common/issues/508
- Coses https://github.com/feathersjs-ecosystem/feathers-hooks-common/issues/455

### CODE REVIEW

**Comment by arfanliaqat** [comment]
Great work @daffl... Been waiting for this... when this gonna be released and available?

**Comment by marshallswain** [comment]
The only question I had was "why would `value` be a function in the `getValue` utility, but I figured it out by the end of the PR.  Looks great!

:shipit:

**Comment by arfanliaqat** [comment]
Great... But the docs have not yet been updated i guess, they still shows soft-delete as DEPRECATED.

**Comment by daffl** [comment]
This is now available as v5.0.x. New softDelete (and other v5) documentation at https://hooks-common.feathersjs.com/hooks.html#softdelete

**Pull request merged**
